stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/raw
      - src/data_loader.py
      - src/preprocessing.py
    params:
      - data.random_state
      - data.test_size
      - preprocessing.remove_outliers
      - preprocessing.scaling
    outs:
      - data/processed

  train:
    cmd: python src/training.py
    deps:
      - data/processed
      - src/training.py
    params:
      - training.model_type
      - training.n_estimators
      - training.max_depth
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluation.py
    deps:
      - models/model.pkl
      - src/evaluation.py
    params:
      - evaluation.threshold
    outs:
      - metrics/metrics.json
