stages:
  preprocess:
    cmd: python src/data/preprocess.py
    deps:
    - data/raw
    - src/data/preprocess.py
    params:
    - data.random_state
    - data.test_size
    - preprocessing.remove_outliers
    - preprocessing.scaling
    outs:
    - data/processed
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed
    - src/models/train.py
    params:
    - training.max_depth
    - training.model_type
    - training.n_estimators
    outs:
    - models/model.pkl
