data:
  raw_path: data/raw/iris_raw.csv
  target_column: species        # MUST match CSV column name exactly
  test_size: 0.2
  random_state: 42

preprocessing:
  scaling: standard              # Iris works best with StandardScaler
  remove_outliers: false         # Iris has no outliers

training:
  model_type: random_forest
  n_estimators: 200
  max_depth: 12
  n_classes: 3                   # Iris is multiclass

evaluation:
  average: macro                 # macro F1 / precision / recall
